name: CI/CD WordPress

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      WP_DB_USER: user
      WP_DB_PASSWORD: poseidon
      WP_DB_NAME: wordpress
      WP_DB_HOST: db:3306
      DOCKER_IMAGE: itform/wordpress-ci

    steps:
      - name: Intégration du code
        uses: actions/checkout@v4

      - name: Vérification Docker
        run: |
          docker --version
          docker compose version || true

      - name: Build de l'image WordPress custom
        run: |
          docker build -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:${{ github.sha }} .

      - name: Lancer docker-compose pour test
        run: docker compose up -d

      - name: Attente MySQL prêt
        run: |
          for i in {1..12}; do
            docker compose exec -T db mysql -h127.0.0.1 -uuser -pposeidon -e "SELECT 1" && break
            sleep 5
          done

      - name: Test WordPress
        run: |
          curl -f http://localhost:8080 || exit 1
          docker compose exec -T db mysql -uuser -pposeidon -e "SHOW DATABASES;"

      - name: Connexion DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DCK_USER }}
          password: ${{ secrets.DCK_TOKEN }}

      - name: Push image WordPress custom
        run: |
          docker push $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:${{ github.sha }}

      - name: Nettoyage local
        if: always()
        run: docker compose down -v

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Copier docker-compose.yml sur le serveur
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SRV_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SRV_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SRV_USER }}/wordpress-app/"


      - name: Connexion SSH et déploiement
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SRV_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SRV_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
          echo "${{ secrets.DCK_TOKEN }}" | docker login -u "${{ secrets.DCK_USER }}" --password-stdin
           cd /home/${{ secrets.SRV_USER }}/wordpress-app
            docker compose pull
            docker compose up -d --remove-orphans

